document.addEventListener('DOMContentLoaded', () => {
    // DOM Elements
    const searchForm = document.getElementById('searchForm');
    const searchInput = document.getElementById('searchInput');
    const resultsSection = document.getElementById('resultsSection');
    const resultsGrid = document.getElementById('resultsGrid');
    const settingsBtn = document.querySelector('.settings-nav');
    const apiModal = document.getElementById('apiModal');
    const closeModalBtn = document.getElementById('closeModal');
    const saveKeysBtn = document.getElementById('saveKeysBtn');
    
    // Modal Logic
    settingsBtn.addEventListener('click', (e) => {
        e.preventDefault();
        apiModal.classList.remove('hidden');
    });

    closeModalBtn.addEventListener('click', () => {
        apiModal.classList.add('hidden');
    });

    apiModal.addEventListener('click', (e) => {
        if (e.target === apiModal) {
            apiModal.classList.add('hidden');
        }
    });

    // Save API Keys securely in localStorage
    saveKeysBtn.addEventListener('click', () => {
        const googleKey = document.getElementById('googleApiKey').value;
        const hibpKey = document.getElementById('hibpApiKey').value;
        
        if (googleKey) localStorage.setItem('osint_google_key', googleKey);
        if (hibpKey) localStorage.setItem('osint_hibp_key', hibpKey);
        
        apiModal.classList.add('hidden');
        alert('Chaves salvas localmente com sucesso!');
    });

    // Load saved keys on open
    document.getElementById('googleApiKey').value = localStorage.getItem('osint_google_key') || '';
    document.getElementById('hibpApiKey').value = localStorage.getItem('osint_hibp_key') || '';

    // Search Form Logic
    searchForm.addEventListener('submit', async (e) => {
        e.preventDefault();
        
        const query = searchInput.value.trim();
        if (!query) return;

        // Show loading state
        resultsSection.classList.remove('hidden');
        resultsGrid.innerHTML = `
            <div class="loader-container">
                <span class="loader"></span>
                <p style="color: var(--text-muted); margin-top: 16px;">Minerando dados em fontes abertas...</p>
            </div>
        `;

        // Simulate API delay / Search Process
        // In a real scenario running on GitHub Pages, this would fetch from a static JSON 
        // generated by GitHub Actions OR make direct fetch() calls to allowed APIs.
        setTimeout(() => {
            performSimulatedSearch(query);
        }, 2000);
    });

    function performSimulatedSearch(query) {
        const filterType = document.getElementById('filterType').value;
        const location = document.getElementById('filterLocation').value;
        const profession = document.getElementById('filterProfession').value;
        const company = document.getElementById('filterCompany').value;
        const birthYear = document.getElementById('filterBirth').value;
        
        resultsGrid.innerHTML = ''; // Clear loader

        // Utility to generate random realistic dates
        const getRandomDate = (startYear, endYear) => {
            const date = new Date(startYear + Math.random() * (endYear - startYear), Math.floor(Math.random() * 12), Math.floor(Math.random() * 28) + 1);
            return date.toLocaleDateString('pt-BR');
        };

        const hash = Math.random().toString(36).substring(2, 10).toUpperCase();

        let mockResults = [];

        // Dynamic result generation based on filter type
        if (filterType === 'person' || filterType === 'document') {
            mockResults.push({
                source: 'Portal da Transparência',
                type: 'gov',
                title: 'Registro em Portal Público',
                content: `Identificada menção a "${query.toUpperCase()}". Pagamento/Licitação número ${hash}-2021 registrado no sistema de despesas.`,
                confidence: 'Alta',
                date: getRandomDate(2021, 2023)
            });
            mockResults.push({
                source: 'Jusbrasil / Escavador',
                type: 'gov',
                title: 'Menção em Diário Oficial',
                content: `Processo nº 10${Math.floor(Math.random()*99999)}-${Math.floor(Math.random()*99)}.2022.8.26.0000. Parte listada como "${query}". Tribunal de Justiça Estadual.`,
                confidence: 'Muito Alta',
                date: getRandomDate(2020, 2023)
            });
            mockResults.push({
                source: 'LinkedIn (OSINT)',
                type: 'social',
                title: 'Associação Profissional',
                content: `Perfil encontrado: ${query}. Experiência prévia em ${company ? company : 'empresas do setor privado'}. Cargo listado é compatível.`,
                confidence: 'Média',
                date: 'Atualizado há 2 semanas'
            });
        }

        if (filterType === 'document') {
            mockResults.push({
                source: 'Receita Federal / CNPJ',
                type: 'gov',
                title: 'Situação Cadastral',
                content: `Documento informado (${query}): Situação ATIVA. Natureza Jurídica formalizada. Endereço base: ${location ? location : 'Omitido na versão pública'}.`,
                confidence: 'Absoluta',
                date: 'Consulta em tempo real'
            });
        }

        if (filterType === 'email') {
            mockResults.push({
                source: 'Have I Been Pwned',
                type: 'leak',
                title: 'Alerta de Vazamento Massivo',
                content: `O e-mail "${query.toLowerCase()}" foi exposto no vazamento "Canva (2019)" e "Collection #1". Senhas associadas ao e-mail foram comprometidas.`,
                confidence: 'Absoluta',
                date: '2019-05-24'
            });
            mockResults.push({
                source: 'Clearbit / Gravatar',
                type: 'social',
                title: 'Metadados de E-mail',
                content: `E-mail associado a uma conta ativa na web. Foto de perfil identificada. Domínio de origem possui registros SPF/DKIM configurados.`,
                confidence: 'Alta',
                date: 'Verificado agora'
            });
        }

        if (filterType === 'username' || filterType === 'email') {
            const username = query.split('@')[0];
            mockResults.push({
                source: 'GitHub API',
                type: 'social',
                title: 'Atividade de Desenvolvedor',
                content: `Identificador "${username}" encontrado. Repositórios públicos listados. Chaves SSH e commits assinados com GPG identificados na conta.`,
                confidence: 'Alta',
                date: 'Último commit: 2023-11-02'
            });
            mockResults.push({
                source: 'Pastebin (Dorks)',
                type: 'leak',
                title: 'Exposição em Dumps Anônimos',
                content: `O texto "${username}" aparece na linha 452 de um paste anônimo indexado no Google (Potencial lista de credenciais botnet).`,
                confidence: 'Baixa',
                date: getRandomDate(2020, 2023)
            });
        }

        if (filterType === 'username' || filterType === 'person') {
            const handle = query.replace(/\s+/g, '').toLowerCase();
            mockResults.push({
                source: 'X / Twitter API',
                type: 'social',
                title: 'Pegada Digital em Redes',
                content: `Conta @${handle} ativa. Análise semântica e horários de postagem apontam localização provável em ${location ? location : 'Região UTC-3'}.`,
                confidence: 'Média',
                date: 'Monitoramento contínuo'
            });
        }

        if (filterType === 'phone') {
            mockResults.push({
                source: 'Truecaller / Whoscall',
                type: 'social',
                title: 'Identificador de Chamadas',
                content: `O número ${query} foi reportado 45 vezes. Tag principal da comunidade: "Cobrança". Nome salvo em agendas de terceiros: "${company ? company : 'Desconhecido'}".`,
                confidence: 'Alta',
                date: 'Consultado Hoje'
            });
            mockResults.push({
                source: 'WhatsApp API',
                type: 'social',
                title: 'Status do Mensageiro',
                content: `Número validado na rede WhatsApp. Possui foto de perfil pública. Recado "Disponível". Conta não comercial.`,
                confidence: 'Absoluta',
                date: 'Verificado agora'
            });
        }

        if (filterType === 'vehicle') {
            mockResults.push({
                source: 'Sinesp Cidadão (Simulação)',
                type: 'gov',
                title: 'Situação de Veículo',
                content: `Placa ${query.toUpperCase()}: HONDA CIVIC EXS, Cor: Prata. Situação: NADA CONSTA (Sem restrições de roubo/furto no sistema nacional).`,
                confidence: 'Absoluta',
                date: 'Consulta em tempo real'
            });
            mockResults.push({
                source: 'Tabela FIPE',
                type: 'gov',
                title: 'Precificação de Ativo',
                content: `Veículo do tipo associado à placa ${query.toUpperCase()} avaliado no mercado atual. Histórico de leilões: Nada indexado publicamente.`,
                confidence: 'Alta',
                date: 'Mês atual'
            });
        }

        if (filterType === 'domain') {
            mockResults.push({
                source: 'Registro.br / WHOIS',
                type: 'gov',
                title: 'Dados do Registrante',
                content: `Domínio ${query.toLowerCase()}: Registrado por ${company ? company : 'Entidade Oculta (Privacy Protect)'}. Servidores DNS apotam para Cloudflare.`,
                confidence: 'Absoluta',
                date: getRandomDate(2018, 2022)
            });
            mockResults.push({
                source: 'Shodan.io',
                type: 'leak',
                title: 'Superfície de Ataque',
                content: `IP alvo associado a ${query.toLowerCase()} possui portas abertas: 80, 443, 22. Header do servidor retorna "nginx/1.18.0 (Ubuntu)".`,
                confidence: 'Alta',
                date: 'Verificado hoje'
            });
            mockResults.push({
                source: 'Wayback Machine',
                type: 'gov',
                title: 'Arquivo Histórico (Archive.org)',
                content: `Domínio ${query.toLowerCase()} possui 320 capturas arquivadas. Primeira captura documentada em 14 de Março de 2016.`,
                confidence: 'Absoluta',
                date: '2016-2023'
            });
        }

        // Treat Homonyms (filtering mock logic)
        let filteredResults = mockResults;
        
        let extraFilters = [];
        if (location) extraFilters.push(`Localização: ${location}`);
        if (profession) extraFilters.push(`Profissão: ${profession}`);
        if (company) extraFilters.push(`Empresa: ${company}`);
        if (birthYear) extraFilters.push(`Nascimento: ${birthYear}`);

        if (extraFilters.length > 0) {
            filteredResults.push({
                source: 'Filtro Avançado Ativo',
                type: 'gov',
                title: 'Refinamento de Dados',
                content: `Resultados foram cruzados usando filtros adicionais (${extraFilters.join(', ')}). Homônimos minimizados.`,
                confidence: 'Muito Alta',
                date: 'Hoje'
            });
        }

        // Render Results
        filteredResults.forEach(result => {
            const card = document.createElement('div');
            card.className = 'result-card glass-panel';
            
            let badgeClass = '';
            if(result.type === 'gov') badgeClass = 'source-gov';
            if(result.type === 'social') badgeClass = 'source-social';
            if(result.type === 'leak') badgeClass = 'source-leak';

            const searchQuery = encodeURIComponent(query + ' "' + result.title + '"');

            card.innerHTML = `
                <div class="card-header">
                    <span class="source-badge ${badgeClass}">${result.source}</span>
                    <span style="font-size: 12px; color: var(--text-muted)">${result.date}</span>
                </div>
                <div class="card-body">
                    <h3 class="card-title">${result.title}</h3>
                    <p>${result.content}</p>
                    <div class="card-footer">
                        <span style="font-size: 12px; color: var(--accent);">
                            <i class="fa-solid fa-check-circle"></i> Confiança: ${result.confidence}
                        </span>
                        <a href="https://www.google.com/search?q=${searchQuery}" target="_blank" class="action-btn">
                            <i class="fa-solid fa-external-link-alt"></i> Buscar
                        </a>
                    </div>
                </div>
            `;
            resultsGrid.appendChild(card);
        });
    }
});
